/dhri/multipleObjectTracking/sub/topic: '/camera/depth_registered/points'
/dhri/multipleObjectTracking/frame/id: '/origin'
/dhri/multipleObjectTracking/pub/points/trackID: '/dhri/points/trackID'
/dhri/multipleObjectTracking/pub/points/filtered: '/dhri/points/filtered'
/dhri/multipleObjectTracking/pub/points/segmented: '/dhri/points/segmented'
/dhri/multipleObjectTracking/pub/points/objectmodel: '/dhri/points/objectmodel'
/dhri/multipleObjectTracking/pub/markers/trackID: '/dhri/markers/trackID'
/dhri/multipleObjectTracking/pub/markers/gaussians: '/dhri/markers/gaussians'
/dhri/multipleObjectTracking/workspace/topic: '/dhri/workspace'
/dhri/multipleObjectTracking/workspace/x: 0.
/dhri/multipleObjectTracking/workspace/y: 0.
/dhri/multipleObjectTracking/workspace/z: 0.
/dhri/multipleObjectTracking/workspace/width: 0.6
/dhri/multipleObjectTracking/workspace/height: 0.5
/dhri/multipleObjectTracking/workspace/zheight: 2.
/dhri/multipleObjectTracking/param/samplingRatio: 5
/dhri/multipleObjectTracking/param/segmentTolerance: 0.07
/dhri/multipleObjectTracking/param/buffernum: 1
/dhri/multipleObjectTracking/gpu/usegpu: true
/dhri/multipleObjectTracking/gpu/particlenumber: 128
/dhri/multipleObjectTracking/gpu/gridsize: 0.02
/dhri/multipleObjectTracking/gpu/newratio: 10
/dhri/multipleObjectTracking/gpu/motionratio: 0.8
